### ISSUE TITLE
iOS ReferenceError w/ GADInterstitialDelegate

### ISSUE THREAD

**Issue by schwer** [EddyVerbruggen/nativescript-admob#10]
I'm seeing the following error on app startup:

app/tns_modules/nativescript-admob/admob.js:22:71: JS ERROR ReferenceError: Can't find variable: GADInterstitialDelegate

**Comment by EddyVerbruggen** [comment]
Sounds like the pod isn't installed (which should happen automatically). What `pod --version` are your running?
