### ISSUE TITLE
NativeScript +angular Cannot find module "nativescript-admob"

### ISSUE THREAD

**Issue by robcaa** [EddyVerbruggen/nativescript-admob#17]
`tns plugin add nativescript-admob`
`tns build android`
build OK

import in app.component.ts:
`import * as Admob from "nativescript-admob";`

tns run android --emulator

> app/app.component.ts(13,24): error TS2307: Cannot find module 'nativescript-admob'.
> TypeScript compiler failed with exit code 1

**Comment by EddyVerbruggen** [comment]
You're doing it right. Perhaps try `tns platform remove android && tns platform add android` as well?

**Comment by robcaa** [comment]
I tried, but no effect.

**Comment by robcaa** [comment]
It's Working!
I changed this line:
`import * as Admob from "nativescript-admob";`
for this:
`var Admob = require("nativescript-admob");`
