### ISSUE TITLE
Banner overlay over content

### ISSUE THREAD

**Issue by nrbn** [EddyVerbruggen/nativescript-admob#23]
The banner comes over my listview and when I have a list of just to cover the screen, the bottom list item becomes invisible, because the banner appears above. And listview does not scrolling.

Are there any css tricks I can do here?

**Comment by EddyVerbruggen** [comment]
Screenshot?

**Comment by nrbn** [comment]
![screenshot_2017-06-14-13-52-36](https://user-images.githubusercontent.com/10879727/27131360-af28e576-510a-11e7-9141-09ab985a8952.png)

**Comment by nrbn** [comment]
![screenshot_2017-06-14-13-52-36](https://user-images.githubusercontent.com/10879727/27131462-0f5d8370-510b-11e7-988a-14a799d0ffd9.png)

**Comment by nrbn** [comment]
![screenshot_2017-06-14-13-52-36](https://user-images.githubusercontent.com/10879727/27131563-73f3b00c-510b-11e7-9e4f-a59a24189336.png)

**Comment by nrbn** [comment]
Admob is over last list item.

**Comment by EddyVerbruggen** [comment]
Yeah you should accomodate for that space, so just render the `ListView` with a bottom margin of 50. Could be done in many ways, fi using a `<GridLayout rows="*, 50"><ListView/><Label row="2" text="Admob banner here"/></GridLayout>.

**Comment by nrbn** [comment]
Thanks. It works!!!!!

**Comment by Skintillion** [comment]
Doesn't work on Tablet the same as Phone. My tablet still overlaps with this.
