### ISSUE TITLE
TypeError: Cannot read property 'addView' of null

### ISSUE THREAD

**Issue by daresh** [EddyVerbruggen/nativescript-admob#26]
After following the installation instructions exactly, and pasting the code into the app:
`const frames = require("ui/frame");
const observableModule = require("data/observable");
const context = new observableModule.Observable();
const gestures = require("ui/gestures");
const socialShareModule = require("nativescript-social-share");
const localize = require("nativescript-localize").localize;
var admob = require("nativescript-admob");

exports.onLoaded = function (args) {
    page = args.object;
    page.bindingContext = context;
    const swipable = page.getViewById("swipable");
    swipable.on(gestures.GestureTypes.swipe, function (args) {
        const swipeDirection = args.direction;
        if (swipeDirection == 1) {
            goToPreviousPage();
        }
    });

    admob.createBanner({
        testing: true,
        size: admob.AD_SIZE.SMART_BANNER,
        //iosBannerId: "ca-app-pub-9517346003011652/3985369721",
        androidBannerId: "ca-app-pub-4966899845463969/8769719340",
        margins: {
            bottom: 50
        }
    }).then(
        function() {
          console.log("admob createBanner done");
        },
        function(error) {
          console.log("admob createBanner error: " + error);
        }
  );
};`

I get the following errors in the console:
`JS: Treating this deviceId as testdevice: 7FB23882623B0AEEC636DCC0E19175C5
JS: admob createBanner done
System.err: com.tns.NativeScriptException:
System.err: Calling js method run failed
System.err:
System.err: TypeError: Cannot read property 'addView' of null
System.err: File: "file:///data/data/com.greenmouseapps.rorschachtest/files/app/tns_modules/nativescript-admob/admob.js, line: 134, column: 55
System.err:
System.err: StackTrace:
System.err:     Frame: function:'', file:'file:///data/data/com.greenmouseapps.rorschachtest/files/app/tns_modules/nativescript-admob/admob.js', line: 134, column: 56
System.err:     Frame: function:'invoke', file:'file:///data/data/com.greenmouseapps.rorschachtest/files/app/tns_modules/tns-core-modules/timer/timer.js', line: 19, column: 48
System.err:     Frame: function:'run', file:'file:///data/data/com.greenmouseapps.rorschachtest/files/app/tns_modules/tns-core-modules/timer/timer.js', line: 23, column: 13
System.err:
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:957)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:941)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:933)
System.err:     at com.tns.gen.java.lang.Runnable.run(Runnable.java:10)
System.err:     at android.os.Handler.handleCallback(Handler.java:751)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
System.err:     at android.os.Looper.loop(Looper.java:154)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6119)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)`

What am I doing wrong?

**Comment by daresh** [comment]
Solved - admob launched too early, added a little timeout and everything works fine :)

**Comment by Skintillion** [comment]
If the user interacts before the ad loads, it will still crash, a timeout is not the solution.
