### ISSUE TITLE
Ads not showing on Android with NativeScript 4

### ISSUE THREAD

**Issue by anaszgh** [EddyVerbruggen/nativescript-admob#32]
Hello,

I have TNS version 4.0.1, a project with Angular.

I have implemented the plugin as guided in the provided link 
[Using the plugin with angular](https://www.thepolyglotdeveloper.com/2016/11/google-admob-nativescript-angular-2/)

But the Ads are not showing, and there is no error.

**Comment by anaszgh** [comment]
I only get these logs after calling the CreateBanner function
```
JS: Treating this deviceId as testdevice: 29406E018A0BED68C02A906CB9B504D3
chromium: [INFO:library_loader_hooks.cc(136)] Chromium logging enabled: level = 0, default verbosity = 0
05-23 13:26:34.194 10592 10592 I cr_BrowserStartup: Initializing chromium process, singleProcess=false
05-23 13:26:34.295 10592 10667 I cr_LibraryLoader: Using linker: org.chromium.base.library_loader.ModernLinker
JS: admob createBanner done
```

**Comment by EddyVerbruggen** [comment]
Did you whitelist that device id? Perhaps try on a simulator as that bypasses whitelisting.

**Comment by anaszgh** [comment]
Do i need to whitelist an android device?? can you please tell me how?

**Comment by EddyVerbruggen** [comment]
No on Android that should not be needed.

**Comment by anaszgh** [comment]
The problem appears on android emulator, do i have to add any xml to contain the Ads?? like AdView (it is needed in native android development).

The callback function returns successfully, but nothing appears.

**Comment by EddyVerbruggen** [comment]
No XML is neede. Usage should be clear if you look at the demo app. Does the demo app work?

**Comment by anaszgh** [comment]
No, the Demo app doesn't work, here are the logs after pressing all buttons

```
05-23 14:30:56.236 17735 17735 I cr_BrowserStartup: Initializing chromium process, singleProcess=false
05-23 14:30:56.392 17735 17799 I cr_LibraryLoader: Using linker: org.chromium.base.library_loader.ModernLinker
JS: admob createBanner done
JS: Treating this deviceId as testdevice: 29406E018A0BED68C02A906CB9B504D3
JS: admob createBanner done
JS: Treating this deviceId as testdevice: 29406E018A0BED68C02A906CB9B504D3
JS: admob createBanner done
JS: Treating this deviceId as testdevice: 29406E018A0BED68C02A906CB9B504D3
JS: admob createBanner done
JS: Treating this deviceId as testdevice: 29406E018A0BED68C02A906CB9B504D3
JS: admob createInterstitial error: 3
JS: Treating this deviceId as testdevice: 29406E018A0BED68C02A906CB9B504D3
JS: admob createBanner done
JS: Treating this deviceId as testdevice: 29406E018A0BED68C02A906CB9B504D3
JS: admob createBanner done
```

**Comment by EddyVerbruggen** [comment]
Care to share a repo reproducing the issue?

**Comment by anaszgh** [comment]
The demo app, i have TNS Version 4.0.1 and it's not working, i'll upload part of the project i'm working on and share it with you shortly.

**Comment by EddyVerbruggen** [comment]
Yeah, you probably mean [this one](https://github.com/EddyVerbruggen/nativescript-admob-demo). I thought there was a demo in the plugin repo (like I have in almost all my other plugins) but there isn't. That demo app was created with NativeScript 3.4 so could very well be there's some incompatibility with 4.

**Comment by anaszgh** [comment]
Yeah, exactly this one i've tried, is there any possibility to make it work on 4?

Also here is a [link](https://github.com/anaszgh/admobissue) for a repository that has the part in my application which runs ads

Thanks.

**Comment by EddyVerbruggen** [comment]
I'm sure it can be fixed because I had to do something similar to fix AdMob with Firebase:

https://github.com/EddyVerbruggen/nativescript-plugin-firebase/commit/674d0aeda5b69f8e478ec56118e173399271d62b

**Comment by anaszgh** [comment]
Can you please guide me on what to do to fix it?

**Comment by anaszgh** [comment]
Thanks!

**Comment by EddyVerbruggen** [comment]
OK, I've just released version 1.4.1 and bumped the demo app to NativeScript 4 and nativescript-admob 1.4.1. Seems to work nicely (see the screenshot below).

Thanks for reporting this issue!

![screenshot_1527080423](https://user-images.githubusercontent.com/1426370/40426053-5ef95d26-5e9a-11e8-9bbe-0c8c709ab2c0.png)

**Comment by anaszgh** [comment]
I have pumbed the version in package.json, removed platforms & node_modules folders
ran the command `npm i`
and the `tns debug android` 
but still the ads not showing :(

**Comment by anaszgh** [comment]
@EddyVerbruggen I have tried the demo App, the SmartBanner appears perfectly fine, but all other types of ads won't!

And the demo app is build using TNS Core, maybe there is a n issue with the Angular Template, can you please try a demo with TNS 4 + Angular, because it is not working for me.

Thanks.

**Comment by RoyiNamir** [comment]
Same here : 

![image](https://user-images.githubusercontent.com/2842123/40578856-6eb65b56-6124-11e8-9cc4-8bf3be42ea28.png)


```
JS: ERROR Error: Uncaught (in promise): false
JS: Treating this deviceId as testdevice: 95D2AA7E57DF5A8FBFB6225CDEC2EF81
JS: admob createBanner done
chromium: [INFO:library_loader_hooks.cc(36)] Chromium logging enabled: level = 0, default verbosity = 0
JS: reference back to player: android.media.MediaPlayer@6b86dcc
JS: whether song playSound completed successfully: undefined
```
Sometimes it shows ad and sometimes it doesn't.
Most of the time it doesn't.

**Comment by EddyVerbruggen** [comment]
I’m nit sure that will help. There’s also nothing specific to Angular/nom-Angular in here. 

Perhaps you’re best off trying the AdMob feature of nativescript-plugin-firebase.
