### ISSUE TITLE
Build error "Could not find common.jar (android.arch.core:common:1.0.0)"

### ISSUE THREAD

**Issue by john-landgrave** [EddyVerbruggen/nativescript-admob#34]
I tried adding this plugin to a {N} 4.1 project today and sometimes when I build I am getting the error I'll paste below. It appears that the following file is simply missing: https://jcenter.bintray.com/android/arch/core/common/1.0.0/common-1.0.0.jar

There is a valid file at https://jcenter.bintray.com/android/arch/core/common/1.1.0/common-1.1.0.jar, but I couldn't find where/how to simply swap the dependency out (I assume that this library is dependent on a library that is dependent on this file?)

Here's the full error:

```[18-06-07 16:25:33.498] (CLI) FAILURE: Build failed with an exception.
[18-06-07 16:25:33.498] (CLI) * What went wrong:
[18-06-07 16:25:33.498] (CLI) Could not resolve all files for configuration ':releaseCompileClasspath'.
[18-06-07 16:25:33.498] (CLI) > Could not find common.jar (android.arch.core:common:1.0.0).
[18-06-07 16:25:33.498] (CLI)   Searched in the following locations:
[18-06-07 16:25:33.498] (CLI)       https://jcenter.bintray.com/android/arch/core/common/1.0.0/common-1.0.0.jar```

Any help on this?

**Comment by skopekreep** [comment]
I'm also experiencing the same errors after upgrade to 4.1, except that I do NOT see a valid file at https://jcenter.bintray.com/android/arch/core/common/1.1.0/common-1.1.0.jar.  

There is, however a valid file located in a nearby folder:  https://jcenter.bintray.com/android/arch/core/common/1.1.1 

named common-1.1.1.jar

I also cannot find where the reference could be changed, even if this updated file was usable.  Any guidance is appreciated.

**Comment by EddyVerbruggen** [comment]
While Googling I found this error all over the web, for many libraries (most of which not related to Firebase or NativeScript). It may be fixed by moving the `jcenter()` repo to the end of the repositories, which is what the change I justed pushed attempts to do.

**Comment by EddyVerbruggen** [comment]
I'm not sure 1.4.2 will actually fix this. Maybe this needs to be reported upstream (NativeScript's Android runtime), but I'd like you to try something because I can't test it (don't have this error).

Can you open <projectroot>/platforms/android/build.gradle, and search for `jcenter()`? Then move it down so it's the last one in the list. For instance:

```
    repositories {
        google()
        jcenter()    <-- must be last
    }
```

You may find it twice, so repeat if necessary please.

Then `tns run android`..

**Comment by john-landgrave** [comment]
Thanks for getting on this, I appreciate it. I will test this with the change you pushed and see if it works, and then if it doesn't I'll tesr moving jcenter down. Will report back likely tomorrow.

**Comment by EddyVerbruggen** [comment]
@john-landgrave It looks like this is a very widespread issue across a lot of different frameworks and plugins. NativeScript seems to have already fixed it for our beloveth framework though: https://github.com/NativeScript/android-runtime/pull/1070 (the trick is to move `jcenter()` to the end of the list of repos.

I think you can try to upgrade tns-android to get the fix: `tns platform add android@next`

**Comment by john-landgrave** [comment]
@EddyVerbruggen I've installed `android@next` as you suggested, but when I try to `tns build android` it creates a `tempPlugin` folder in my `platforms` folder which only contains a `nativescript-admob` folder which then contains a `build.gradle` which has `jcenter()` above `google()`, even though I've changed this in my `platforms/android/build.gradle`. Sorry to be bothering you about this, but I feel like I've got all my ducks lined up but one and I'm just not sure where it is?

**Comment by EddyVerbruggen** [comment]
@john-landgrave FYI The fix has actually been released so no need for `@next` anymore - make sure you have tns-android `4.1.3` or higher. Perhaps the `@next` version didn't update correctly, so you might want to give 4.1.3 a try.
