### ISSUE TITLE
Banner Ads Not Vissible For Multiple Pages

### ISSUE THREAD

**Issue by pointdeveloper** [EddyVerbruggen/nativescript-admob#4]
The Plugin works fine for a single page. But if you have Multiple Page when the second page loads it covers the entire screen and the ad is not visible.

i use the following to navigate to the second page
` frameModule.topmost().navigate("secondPage")`

**Comment by calebeaires** [comment]
You must call admob again and again, for each page!

**Comment by Mflm** [comment]
I have the same problem with the lastest version.

Any idea?
Thanks
