### ISSUE TITLE
How to check when ad is closed?

### ISSUE THREAD

**Issue by Omi231** [EddyVerbruggen/nativescript-admob#44]
In previous version of this plugin, when using admob.createInterstititial we were able use  onAdClosed event which was very useful. After I updated this plugin I am unable to do the same. Is there any way I can call a function when the ad is closed?

**Comment by EddyVerbruggen** [comment]
How did you use it exactly?

**Comment by Omi231** [comment]
In previous version of plugin, i was calling `createInterstitial` when user taped on a button and then was listening to ad Close event to download a file. Now because i can't listen the even I have stopped using interstitials which has decreased my revenue from the app.

**Comment by EddyVerbruggen** [comment]
Have you considered sending a PR to fix the issue?

**Comment by Omi231** [comment]
> Have you considered sending a PR to fix the issue?

Sorry, it is beyond my skill level.

**Comment by EddyVerbruggen** [comment]
I'm not sure how you've been previously been able to use the `onAdClosed` event through the plugin API, but I'll add official support for it today.

**Comment by EddyVerbruggen** [comment]
3.1.0 is now available, see the updated readme @ `onAdClosed`.
