### ISSUE TITLE
Interstitial Error : Cannot read property 'getContentResolver' of undefined

### ISSUE THREAD

**Issue by pointdeveloper** [EddyVerbruggen/nativescript-admob#5]
Hey there,
The error message when trying to show Interstitial Twice on NativeScript version 1.7.0

`JS: admob createInterstitial error: TypeError: Cannot read property 'getContentResolver' of undefined`

The error Does not appear on previous versions of NativeScript.
The error Does not appear when showing Interstitial ads for the first time..It appears when trying to show ads More than once.

I have checked this on Android 4.4 and 5.0

-Thanks

**Comment by EddyVerbruggen** [comment]
Hi @pointdeveloper,

Thanks for reporting this! I've just released 1.1.5 which fixes this issue.
