### ISSUE TITLE
Failed to find module: "nativescript-admob", relative to: app/tns_modules/

### ISSUE THREAD

**Issue by hhloi** [EddyVerbruggen/nativescript-admob#56]
![image](https://user-images.githubusercontent.com/3298194/53540521-751c8c00-3b48-11e9-90d7-1f882834e078.png)

**Comment by hhloi** [comment]
i try you plugin , but not work
![image](https://user-images.githubusercontent.com/3298194/53540564-9ed5b300-3b48-11e9-9013-1251c04fe186.png)

**Comment by EddyVerbruggen** [comment]
This plugin is not part of the Preview app, so that's to be expected.

**Comment by hhloi** [comment]
I follow this link , it didnot work
https://github.com/EddyVerbruggen/nativescript-admob-demo
