### ISSUE TITLE
Error in admob.createBanner: TypeError: Cannot read property 'android' of undefined

### ISSUE THREAD

**Issue by ilyago** [EddyVerbruggen/nativescript-admob#6]
Error in admob.createBanner: TypeError: Cannot read property 'android' of undefined

on Genymotion S4 android 4.4

**Comment by EddyVerbruggen** [comment]
Could you please elaborate? At which moment are you calling the function? Perhaps "too early"?

**Comment by ilyago** [comment]
Inside end of the pageloaded function

**Comment by EddyVerbruggen** [comment]
Please check the commented example [here](https://github.com/EddyVerbruggen/nativescript-admob-demo/blob/master/AdMob/app/main-page.js). On Android this indeed didn't work before plugin version 1.1.4 which I just released.

**Comment by TeorikDeli** [comment]
@EddyVerbruggen I have the same problem with 1.1.5 version on Android Simulator (I also tried your example). My Google Play Services API version is 31 (which is latest).

Thanks.
