### ISSUE TITLE
Interstitial AD show only first time when navigating to another page

### ISSUE THREAD

**Issue by rahadur** [EddyVerbruggen/nativescript-admob#61]
Hello @EddyVerbruggen i have a problem with **`preloadInterstitial`** when i first time **navigate** from my Home to Details Page **`preloadInterstitial`** & **`showInterstitial`** work as expected. but when i back to Home Page  and renavigate to Details Page this time nothing  is showing. not even my test **Interstitial**

```typescript

// Details Page page Loaded Event
export function onPageLoaded(args: EventData) {
    preloadInterstitial({
        testing: true,
        androidInterstitialId: "ca-app-pub-3940256099942544/1033173712", 
        onAdClosed: function () { console.log("interstitial closed") }
    }).then(
        function() {
            
            // CALLED  showInterstitial when ad is preload.
            // Only work on first time called.
            setTimeout(() => {
                showInterstitialAd();
            }, 50000);

        },
        function(error) {
            console.log("admob preloadInterstitial error: " + error);
        }
    );
}


// Show Interstitial Ad
function showInterstitialAd() {
    showInterstitial().then(
        function() {
            console.log("interstitial showing");
        },
        function(error) {
            console.log("admob showInterstitial error: " + error);
        }
    )
}
```
**Note:** I called **showInterstitialAd()** inside preloadInterstitial promise after a long time in **setTimeout()**

### package.json
```javascript
{
  "nativescript": {
    "id": "app.xplatform.myapp",
    "tns-android": {
      "version": "5.3.1"
    },
    "tns-ios": {
      "version": "5.3.1"
    }
  },
  "dependencies": {
    "nativescript-admob": "^3.3.2",
    "nativescript-fresco": "5.2.0",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-ui-listview": "^6.1.0",
    "tns-core-modules": "~5.3.0"
  }
}
```

### Environment
```console
λ tns doctor
√ Getting environment information

No issues were detected.
√ Your ANDROID_HOME environment variable is set and points to correct directory.
√ Your adb from the Android SDK is correctly installed.
√ The Android SDK is installed.
√ A compatible Android SDK for compilation is found.
√ Javac is installed and is configured properly.
√ The Java Development Kit (JDK) is installed and is configured properly.
√ Local builds for iOS can be executed only on a macOS system. To build for iOS on a different operating system, you can use the NativeScript cloud infrastructure.
√ Getting NativeScript components versions information...
‼ Update available for component nativescript. Your current version is 5.3.1 and the latest available version is 5.3.2.
√ Component tns-core-modules has 5.3.1 version and is up to date.
√ Component tns-android has 5.3.1 version and is up to date.
√ Component tns-ios has 5.3.1 version and is up to date.
```

### Log
**First time navigate to details page**
```console
JS: Treating this deviceId as testdevice: D8B96603C82D1318E94C52733B7D985B
JS: onAdLoaded
JS: interstitial preloaded - you can now call 'showInterstitial' whenever you're ready to do so
ActivityManager: START u0 {cmp=app.xplatform.myapp/com.google.android.gms.ads.AdActivity (has extras)} from uid 10194 and from pid 13360 on display 0
JS: interstitial showing
```
**Second time navigate to details page**
```console
JS: Treating this deviceId as testdevice: D8B96603C82D1318E94C52733B7D985B
JS: onAdLoaded
```

**Comment by EddyVerbruggen** [comment]
Are you preloading the second time?

**Comment by rahadur** [comment]
Yes I'm preload when Details Page is Loaded.

**Comment by EddyVerbruggen** [comment]
Perhaps it has to do with the 50 second delay between preload and show? If you want to delay showing the banner by that much, then you better also delay preloading because now you're often preloading while not needing to show an ad anyway.. and that may not be allowed by Google. Guessing here..

**Comment by rahadur** [comment]
No, It's not work. 😓 Details Page Interstitial AD show only one time until i close my app & reopen it.! 

```typescript 
export function onPageLoaded(args: EventData) {
    setTimeout(() => {
        loadInterstitial();
    }, 5000);
}
```

```typescript
function loadInterstitial() {
    preloadInterstitial({
        testing: true,
        androidInterstitialId: "ca-app-pub-3940256099942544/1033173712", 
        onAdClosed: function () { console.log("interstitial closed") }
    }).then(
        function() {
            setTimeout(() => {
                showInterstitialAd();
            }, 5000);
        },
        function(error) {
            console.log("admob preloadInterstitial error: " + error);
        }
    );
```

This is the place where i have to show AD most of the time. 😞

**Comment by EddyVerbruggen** [comment]
Can you check if the demo app in this repo has the same issue?

**Comment by rahadur** [comment]
Ok i found the problem.! The problem is that `preloadInterstitial()` promis called only once when it's first time preloaded Interstitial AD after that it will never called this promise anywhere in entire application. 

```typescript
preloadInterstitial({
        testing: true,
        androidInterstitialId: "ca-app-pub-3940256099942544/1033173712", 
        onAdClosed: function () { console.log("interstitial closed") }
    }).then(
        function() {     
             // This Promise called only once when preloadInterstitial() called first time.
             // once it called it will naver called in entire application lifecycle. 
             // until app is closed and reopen.
        },
        function(error) {
            console.log("admob preloadInterstitial error: " + error);
        }
    );
```

### Possible Solution: 

```typescript
preloadInterstitial({
        testing: true,
        androidInterstitialId: "ca-app-pub-3940256099942544/1033173712", 
        onAdLoaded: function () {
           // REQUESTED EVENT
           console.log("interstitial Loaded") 
        },
        onAdClosed: function () { console.log("interstitial closed") }
    }).then(
        function() {
             // This block call only one time in entire application lifecycle. 
             console.log("interstitial preloaded"); 
         },
        function(error) {
            console.log("admob preloadInterstitial error: " + error);
        }
    );
```

I am requesting for a new `onLoadedAd` Event at  `preloadInterstitial()`  it's essential because if i want to automatically called `showInterstitial()` after a short period of time **onLoadedAd()** event called is necessary.

**Comment by EddyVerbruggen** [comment]
@rahadur I don't understand *why* the promise is not resolved when you invoke `preloadInterstitial` for a second time. I mean, this should resolve it the second time as well:

https://github.com/EddyVerbruggen/nativescript-admob/blob/402c9ffc63a9e8a8972d55697a3e665e27da8a99/src/admob.android.js#L175

Any idea why in your app it doesn't?

**Comment by jayhaluska** [comment]
I got the samue issue. I call `preloadInterstitial()` after execution of `showInterstitial()`, but the second time, the promise is not resolved.

**Comment by andreacimino** [comment]
After several hours I figured out the problem, and the answer is in the nativescript-plugin-firebase:

`export function preloadInterstitial(arg: InterstitialOptions): Promise<any> {
  return new Promise((resolve, reject) => {
    try {
      const settings = firebase.merge(arg, BANNER_DEFAULTS);
      const activity = appModule.android.foregroundActivity || appModule.android.startActivity;
      firebase.admob.interstitialView = new com.google.android.gms.ads.InterstitialAd(activity);
      firebase.admob.interstitialView.setAdUnitId(settings.androidInterstitialId);

      // need these to support preloadInterstitial more than once
      this.resolve = resolve;
      this.reject = reject;
`

Seems the resolve must be save in a this variable, otherwise the context changes.
This patch is not presenti in the nativescript-admob plugin.

**Comment by EddyVerbruggen** [comment]
Hmm, makes sense. That's a very recent change. Would you mind doing a PR?

**Comment by andreacimino** [comment]
I made the pull request.

Il giorno mer 20 nov 2019 alle ore 17:28 Eddy Verbruggen <
notifications@github.com> ha scritto:

**Comment by alexisconsuegra** [comment]
Hello,
Why do I get error "<Google> To get test ads on this device, set: request.testDevices = @[ @"6a08b8cca00a33ad944a728ea4114fc5" ]; " 
Thanks
