### ISSUE TITLE
plugin does not work on iOS

### ISSUE THREAD

**Issue by mohamnag** [EddyVerbruggen/nativescript-admob#62]
using tns version 5.3.1 and running on iOS 12.1, I can't get the basic setup of this plugin running. I'm always getting following error in the logs:
```bash
CONSOLE LOG file:///app/tns_modules/nativescript-admob/admob.js:145:18: Error in admob.createBanner: TypeError: GADRequest.request is not a function. (In 'GADRequest.request()', 'GADRequest.request' is undefined)
CONSOLE LOG file:///app/app/admob.service.js:40:24: admob createScreenBottomBanner error: TypeError: GADRequest.request is not a function. (In 'GADRequest.request()', 'GADRequest.request' is undefined)
```

**Comment by EddyVerbruggen** [comment]
Plz share a repo showing the issue, and reopen. But first try removing the platforms folder, and don't run this inside the Preview app.

**Comment by bowlesns** [comment]
I'm getting this error too. I'm using a button that calls the function

`import * as Admob from "nativescript-admob";
`


```
        createBanner() {
            Admob.createBanner({
                testing: true,
                size: Admob.AD_SIZE.MEDIUM_RECTANGLE,
                iosBannerId: "<USING-TEST-AD-ID>",
                // androidBannerId: this.androidBannerId,
                // iosTestDeviceIds: ["<ADDED-SIMULATOR'S ID>"],
                margins: {
                    bottom: 0
                }
            }).then(function() {
                console.log("admob createBanner done");
            }, function(error) {
                console.log("admob createBanner error: " + error);
            });
        }
```

I deleted the platforms folder and did a pod repo update as well.  Does the plugin not work with the iphone simulator, or am I doing something wrong? Any help would be greatly appreciated!

**Comment by mohamnag** [comment]
@bowlesns I didn't manage to make it run either. for now I gave up as iOS is not my main concern but if anyone found a way to make it run it might be nice to have it up and running.

One thing that could help might be setting the view property explicitly. I took a short look at the code and it seems if view is not set, it will try to find a proper one automatically, might be that does not work.

**Comment by bowlesns** [comment]
I have a feeling my issue is due to angular routing/scope issues. The demo app runs fine and displays the ads, but can't get my app to play nicely.

**Comment by bowlesns** [comment]
@mohamnag @EddyVerbruggen  I figured out what the issue was for me.
 My tns-ios version was 5.3.1 as well, after changing to 5.1.0 it works properly.

If anyone stumbles upon this, you can change this in the package.json file in the root of your {N} project. Remember to remove package-lock.json, and delete the platforms/ios and node_modules directories in your project prior to build/run.

**Comment by mohamnag** [comment]
@bowlesns thanks for letting me know. this is definitely no _solution_ but will do as for now. However I can imagine soon this will bring other problems as TNS moves on.

**Comment by EddyVerbruggen** [comment]
Yeah I agree. The question is: which _exact_ version of tns-ios started to become incompatible. If we know that, it will probably be easier to pinpoint the exact change in tns-ios caused the incompatibility.

**Comment by mohamnag** [comment]
The thing is, that it seems to me it also stopped showing ads even on
Android. Some of the users of my app who know me, reported that ads are not
showing up in recent version of the app. I have to investigate more but it
seems the functionality is not very stable even in Android.

**Comment by EddyVerbruggen** [comment]
If I were you I'd contact AdMob and ask them what's up with your app id's. It's not uncommon for them to suspend apps receiving ads because of unexpected/strange activity.
