### ISSUE TITLE
Hardcoding Symbols

### ISSUE THREAD

**Issue by mudlabs** [EddyVerbruggen/nativescript-admob#73]
How where you able to log out the values of these symbols? 
https://github.com/EddyVerbruggen/nativescript-admob/blob/5579cae0837d4bcf3df5e5379ddd5ca942f03e08/src/admob.ios.js#L38

I'm trying to find the value of `kGADAdLoaderAdTypeUnifiedNative`. I've tried;
  - `tns debug ios`
  - `tns debug ios --debug-brk`
  - `npm run demo.ios --debug-brk`

But all I ever get is the error;
  - Metadata for "GoogleMobileAds.kGADAdLoaderAdTypeUnifiedNative" found but symbol not available at runtime

**Comment by EddyVerbruggen** [comment]
Did you try `console.log("kGADAdLoaderAdTypeUnifiedNative: " + kGADAdLoaderAdTypeUnifiedNative)`? Otherwise IDK..

**Comment by mudlabs** [comment]
Yep; doesn't output.

**Comment by mudlabs** [comment]
It's ___"6"___ [StackOverflow](https://stackoverflow.com/questions/57900833/need-the-value-of-a-google-mobile-ads-sdk-constant).
