### ISSUE TITLE
Banner disappears

### ISSUE THREAD

**Issue by Mflm** [EddyVerbruggen/nativescript-admob#76]
Hi,

I would like a banner in each page of my application, but when I change the page the banner disappears.

I know I have to reload the banner on each page but it doesn't work, only on the first load

Any idea?

Thanks

**Comment by Mflm** [comment]
With a timer works!

**Comment by gaboisleno** [comment]
can you please share your project? I have problems to show ads :(

**Comment by Mflm** [comment]
With a timer

timer.setTimeout(() => {
	exports.createBanner();
	}, 2000);

**Comment by gaboisleno** [comment]
> 
> 
> With a timer
> 
> timer.setTimeout(() => {
> exports.createBanner();
> }, 2000);

Yes, i have a timer in the init event, also tried with your demo app, but always same result.
I'm really confused about why doesn't work

    ngOnInit(): void {
        setTimeout(this.createBanner, 2000);
    }

**Comment by gaboisleno** [comment]
> With a timer
> 
> timer.setTimeout(() => {
> exports.createBanner();
> }, 2000);

Thank you so much!
