### ISSUE TITLE
Ads not showing

### ISSUE THREAD

**Issue by gaboisleno** [EddyVerbruggen/nativescript-admob#78]
Hello, I'm trying to use this module but I have the next issue either livesync or builded apk.
I created a banner using Nativescript 6.3.0, but is not showing spite of have no errors.

This my code (admob banner test: ca-app-pub-3940256099942544/6300978111)

```
var Admob = require("nativescript-admob");
    createBanner() {
        Admob.createBanner({
            testing: true,
            size: Admob.AD_SIZE.SMART_BANNER,
            androidBannerId: "ca-app-pub-3940256099942544/6300978111",
            margins: {
                bottom: 0
            },
        }).then(() => {
            console.log("admob createBanner done");
        }, error   => {
            console.log("admob createBanner error: " + error);
        });
    }

```
I added next lines in the mainfest.xml too (example value)
```
<!-- AdMobs -->
        <meta-data 
            android:name="com.google.android.gms.ads.APPLICATION_ID" 
            android:value="ca-app-pub-123123123123~AAAAAA" />
```
Finally, the console output shows me no problems
```
JS: Treating this deviceId as testdevice: 2E68431BAF1F006604E80289E704D105
chromium: [INFO:library_loader_hooks.cc(143)] Chromium logging enabled: level = 0, default verbosity = 0
JS: admob createBanner done
```
But no bannes shows.
Could you please help me? Thanks a lot

**Comment by ramkaranyadav18** [comment]
I also faced the same issue. This [workaround](https://github.com/EddyVerbruggen/nativescript-admob/issues/15#issuecomment-282481758) worked for me. It might help you as well.

**Comment by gaboisleno** [comment]
> I also faced the same issue. This [workaround](https://github.com/EddyVerbruggen/nativescript-admob/issues/15#issuecomment-282481758) worked for me. It might help you as well.

I fixed with a timer

    timer.setTimeout(() => {
    exports.createBanner();
    }, 2000);
