### ISSUE TITLE
ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted

### ISSUE THREAD

**Issue by ahmetceylan** [EddyVerbruggen/nativescript-admob#84]
Hi, I think you should update the pod version of "Google-Mobile-Ads-SDK". 
I tried to upload a new application to App Store but it gave "Deprecated API Usage" error.  
After I did some research, I found below post; it seems UIWebView references are removed from Google Mobile Ads on 21 Feb. 

https://github.com/firebase/firebase-ios-sdk/issues/3862#issuecomment-589726744

Note: After I updated the pod version to '7.59.0' manually , deprecated api issue is fixed.

**Comment by EddyVerbruggen** [comment]
That's good to know, thanks!
I'll upgrade and test this.

**Comment by EddyVerbruggen** [comment]
4.1.0 has been published to npm. It may not look like it, but running ` npm view nativescript-admob` reveals it indeed has.

**Comment by ahmetceylan** [comment]
Great! thanks for quick response.
